import React, { useState, useEffect } from 'react';
import { NextPage, GetServerSideProps } from 'next';
import ErrorPage from 'next/error';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Data } from '../types/DataType';
import Table from '../components/table';
import Filter from '../components/filter';
import Checkbox from '../components/checkbox';
import { rows } from '../components/rows';

type Props = {
  data: Data[];
};

const Home: NextPage<Props> = function Home({ data }) {
  if (!data) {
    return <ErrorPage statusCode={404} />;
  }

  const [diyChecked, setDiyChecked] = useState(false);
  const [printerChecked, setPrinterChecked] = useState(false);
  const [rawData, setRawData] = useState(data);
  const [filteredData, setFilteredData] = useState(data);

  const filterTable = () => {
    let filteredTableData = rawData;
    if (diyChecked) {
      filteredTableData = filteredTableData.filter((column) => column.diyKit === true);
    }
    if (printerChecked) {
      filteredTableData = filteredTableData.filter((column) => column.builtPrinter === true);
    }
    setFilteredData(filteredTableData);
  };

  useEffect(() => {
    filterTable();
  }, [diyChecked, printerChecked, rawData]);

  const handleChange = (key) => {
    if (key === 'diyKit') {
      setDiyChecked(!diyChecked);
    } else {
      setPrinterChecked(!printerChecked);
    }
  };

  const handleFilterChange = async (e: any) => {
    const text = e.target.value;
    const res = await fetch(`http://localhost:8000/api/list?search=${text}`); // todo
    const json = await res.json();
    setRawData(json);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Filter onChange={handleFilterChange} />
        <Checkbox label="DIY Kit" onChange={handleChange.bind(null, 'diyKit')} />
        <Checkbox label="Build printer" onChange={handleChange.bind(null, 'builtPrinter')} />
        <Table data={filteredData} rows={rows} />
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  try {
    const res = await fetch(`http://${req.headers.host}/api/list`); // todo
    const json = await res.json();

    return {
      props: {
        data: json,
      },
    };
  } catch (error) {
    return {
      props: {},
    };
  }
};

export default Home;
